# Generated by Django 5.2.5 on 2025-09-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
