# Generated by Django 5.2.5 on 2025-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_drive_file_id_document_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='web_content_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
